### ISSUE TITLE
Vertaisarviointi

### ISSUE THREAD

**Issue by dhaap** [mlkulmala/TiLa-reitinhaku#2]
Kloonattu 00:55 10.10.2020

### Toimivuus
Käyttöliittymä on todella siisti ja toimii hyvin. Reitin haku toimii molemmilla algoritmeillä. Kohtasin ongelman reittien haussa, jossa ikkuna jäätyy kummallakin algoritmillä, jos aloitus ja loppu pisteiden välinen reitti on tarpeeksi monimutkainen.
<br />

### Koodi
Helposti luettavat luokat, ja mikään ei vaikuttanut sekavalta. Itse henkilökohtaisesti olisin ehkä antanut mielummin x ja y arvon solmulle ja jättänyt Ruutu luokan tekemättä, mutta tämä on vain henkilökohtainen preferenssi. Sovellus logiikan jakaminen eri paketteihin olisi ehkä hyvä idea, mutta se ei vaikuta sovelluksen toimintaan. Olisi järkevää eriyttää A* algortimi ja Fringe samasta luokasta eri luokkiin. Itse tuotin, myös Fringe search algoritmin omassa projektissa ja voin lämpimästi suositella käyttämään kahta eri taulukkoa cacheksi. Myös oma ArrayList toteutus on todella helppo toteuttaa katsomalla esim. OHJA mooc materiaalia.  Vielä loppu vinkkinä Fringeä varten, niin voit käyttää kahta eri listaa now ja lateria varten, jos se helpottaa linkitettylista on todennäköisesti nopeampi. Olisi ollut myös kiinnostavaa nähdä molempien algoritmien suorituksessa menevä aika, jotta niitä voisi vertailla.
Todella hyvää koodia ja kiinnostava projekti isot tsempit vielä loppusuoralle.
<br />

### Testit
Kaikki testit menivät läpi ja näyttivät todella hyviltä.

**Comment by mlkulmala** [comment]
Hei! Kiitos kommenteista. En päätynyt käyttämään kahta eri listaa vaan jatkoin linkitetyllä listalla, mutta ajatuksen palauttaminen kahteen listaan (now ja later) auttoi löytämään virheen koodista, mikä oli siis syy sille, että vähänkin monimutkaisemmat haut jumittuivat. Olin lisännyt solmuja väärään kohtaan listaa :)
